class Car:
    @property
    def id(self) -> int: ...
    @property
    def path(self) -> list[int]: ...

class Intersection:
    @property
    def id(self) -> int: ...
    @property
    def streets(self) -> list[int]: ...
    @property
    def used_streets(self) -> list[int]: ...
    @property
    def used(self) -> bool: ...
    @property
    def non_trivial(self) -> bool: ...

class Street:
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def used(self) -> bool: ...
    @property
    def length(self) -> int: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def total_cars(self) -> int: ...

class CityPlan:
    def __init__(self, filename: str) -> None: ...
    @property
    def intersections(self) -> list[Intersection]: ...
    @property
    def streets(self) -> list[Street]: ...
    @property
    def cars(self) -> list[Car]: ...
    @property
    def duration(self) -> int: ...
    @property
    def bonus(self) -> int: ...
