from .city_plan import CityPlan

class Schedule:
    @property
    def length(self) -> int: ...
    @property
    def duration(self) -> int: ...
    @property
    def order(self) -> list[int]: ...
    @property
    def times(self) -> list[int]: ...
    def relative_order(self) -> list[int]: ...
    def set(self, order: list[int], times: list[int], relative_order: bool = False) -> None: ...
    def set_default(self) -> None: ...
    def set_adaptive(self) -> None: ...

class Simulation:
    def __init__(self, city_plan: CityPlan) -> None: ...
    def load_schedules(self, filename: str) -> None: ...
    def save_schedules(self, filename: str) -> None: ...
    def default_schedules(self) -> None: ...
    def adaptive_schedules(self) -> None: ...
    def set_schedules(
        self,
        schedules: list[tuple[list[int], list[int]]],
        relative: bool = True
    ) -> None: ...
    def score(self) -> int: ...
    def summary(self) -> None: ...
    @property
    def schedules(self) -> dict[int, Schedule]: ...

def default_simulation(city_plan: CityPlan) -> Simulation: ...
def adaptive_simulation(city_plan: CityPlan) -> Simulation: ...
