default:
    image: ubuntu:latest
    before_script:
        - apt-get update -y && apt-get upgrade -y
        - apt-get install -y build-essential git python3-venv python3-dev python3-pip
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r requirements-test.txt


build_test_package_cpp:
    allow_failure: true
    script:
        - pip install cmake
        - mkdir build && cd build
        - cmake ../traffic_signaling -DBUILD_PYBIND_MODULES=ON
        - cmake --build . --config Release -j 16
        - ctest -C Release -V --output-on-failure


build_test_package_python:
    allow_failure: true
    script:
        - pip install ./traffic_signaling
        - python3 -m unittest discover -s traffic_signaling/tests


test_optimizer:
    allow_failure: true
    script:
        - pip install -r requirements.txt
        - cythonize -3a operators.py
        - python3 -m unittest discover -s tests


thesis_pdf:
    image: aergus/latex
    before_script:
        - cd thesis
    script:
        make all
    artifacts:
        paths:
            - thesis/thesis.pdf
            - thesis/abstract-cs.pdf
            - thesis/abstract-en.pdf
        expire_in: "7 days"