default:
    image: ubuntu:latest
    before_script:
        - apt-get update -y && apt-get upgrade -y
        - apt-get install -y build-essential python3-venv python3-dev python3-pip


build_test_cpp:
    allow_failure: true
    script:
        - pip install cmake
        - mkdir build && cd build
        - cmake ../traffic_signaling
        - cmake --build . --config Release -j 10
        - ctest -C Release -V --output-on-failure


build_test_python:
    allow_failure: true
    script:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r requirements.txt

        - python3 traffic_signaling/tests/test_io.py
        - python3 traffic_signaling/tests/test_score.py
        - python3 traffic_signaling/tests/test_time.py
