default:
    image: python:3.13
    before_script:
        - gcc --version
        # `git` is required by `FetchContent` in `CMakelists.txt`
        - git --version
        - python3 -V
        - python3 -m venv .venv
        - source .venv/bin/activate
        - pip install -r requirements-test.txt


test_package_cmake:
    allow_failure: true
    script:
        # `git` is required by `FetchContent` in `CMakelists.txt`
        - git --version
        - pip install cmake
        - cmake --version
        - make test_package_cmake


test_package_python:
    allow_failure: true
    script:
        - pip install ./traffic_signaling
        - make test_package_python


test_optimizer:
    allow_failure: true
    script:
        - pip install -r requirements.txt
        - make test_optimizer


thesis_pdf:
    image: aergus/latex
    allow_failure: true
    before_script:
        - cd thesis
    script:
        - make all
    artifacts:
        paths:
            - thesis/thesis.pdf
            - thesis/abstract-cs.pdf
            - thesis/abstract-en.pdf
        expire_in: 7 days
