default:
    image: ubuntu:latest
    before_script:
        - apt-get update -y && apt-get upgrade -y
        - apt-get install -y build-essential git python3-venv python3-dev python3-pip
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install -r traffic_signaling/tests/requirements.txt


build_test_cpp:
    allow_failure: true
    script:
        - pip install cmake
        - mkdir build && cd build
        - cmake ../traffic_signaling -DBUILD_PYBIND_MODULES=ON
        - cmake --build . --config Release -j 12
        - ctest -C Release -V --output-on-failure


build_test_python:
    allow_failure: true
    script:
        - pip install -r requirements.txt
        - python3 -m unittest discover -s traffic_signaling/tests
