default:
    image: ubuntu:latest


build_test_cpp:
    allow_failure: true
    before_script:
        - apt-get update -y && apt-get upgrade -y
        - apt-get install -y cmake
    script:
        - mkdir build && cd build
        - cmake ../simulation
        - cmake --build . --config Release -j 10

        - ./test_basic ../input_data/b.txt
        - ./test_time ../input_data/d.txt


build_test_python:
    allow_failure: true
    before_script:
        - apt-get update -y && apt-get upgrade -y
        - apt-get install -y python3-venv
    script:
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install --upgrade pip
        - pip install -r requirements.txt

        - python3 simulation/tests/test_io.py
        - python3 simulation/tests/test_score.py
        - python3 simulation/tests/test_time.py
