from ..city_plan import CityPlan

class Schedule:
    def set_schedule(self, times:list[int], order:list[int]) -> None: ...
    @property
    def length(self) -> int: ...
    @property
    def duration(self) -> int: ...

class Simulation:
    def __init__(self, city_plan:CityPlan) -> None: ...
    def read_plan(self, filename:str) -> None: ...
    def write_plan(self, filename:str) -> None: ...
    def create_plan_default(self) -> None: ...
    def run(self) -> Simulation: ...
    def score(self) -> int: ...
    def summary(self) -> None: ...
    @property
    def schedules(self) -> dict[int, Schedule]: ...
